name: Petrichor Tests

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: SetUp environment vars
      run: echo "Environment variable set"
      env:
        FORGET_KEY: ${{ vars.FORGET_KEY }}
        FORGET_SALT_KEY: ${{ vars.FORGET_SALT_KEY }}
        SECRET_KEY: ${{ vars.SECRET_KEY }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Petrichor Django Testing
      run: |
        python3 manage.py test app/tests --keepdb
